version: '3.8'
services:
  backend:
    container_name: backend
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb
    depends_on:
      - db
    volumes:
      - .:/wwt
      - /wwt/node_modules
    networks:
      wwt-network:
  frontend:
    container_name: frontend
    build:
      dockerfile: frontend/Dockerfile
      context: .
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - .:/wwt
      - /wwt/node_modules
    networks:
      wwt-network:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
    networks:
      wwt-network:
#volumes:
#  pgdata:

networks:
  wwt-network:
